### ISSUE TITLE
Windows or Mac theme?

### ISSUE THREAD

**Issue by jedmao** [DustinBrett/x#2]
What's with the Mac icons on the Windows theme? 😂

**Comment by DustinBrett** [comment]
Haha. Ya it's meant to be a bit of a hybrid/Frankenstein. This combo is the things I prefer from both OS's as I use both on a daily basis. I hope in the not too distant future to generalize my styling of components a bit more so that things can be mixed and matched. At that point I'd like to have all UI components for macOS and Windows (dark & light themes) and allow the user to change it. Until then, noted/closing... :-)
