### ISSUE TITLE
Clicking between "x" and "-" sometimes maximizes window

### ISSUE THREAD

**Issue by jedmao** [DustinBrett/x#3]
There is also dead space between the ❌  ➖ and ➕ icons. I know this is something you took from macOS that you liked, but the amount of precision required to get the desired outcome is not ideal.

Not that this is being distributed to millions of people or anything! 😛

**Comment by DustinBrett** [comment]
Thank you for the feedback. I haven't had much of the issue you describe on desktop but indeed on mobile it can be hard. Also in regards to "dead space", could you clarify what you mean? Do you mean areas within the button which clicking does nothing? If so it sounds like I may have the click target on the svg instead of the entire circle. Either way I will add this to my notes and work on making the click targets easier. May I ask what devices you tested this issue with?

**Comment by jedmao** [comment]
This was on Windows 10 Desktop and yeah, I mean you click and nothing (or the wrong thing) happens.

**Comment by DustinBrett** [comment]
Thanks. I'll look into making this better.

**Comment by DustinBrett** [comment]
I've increased the click targets. As for the wrong thing happening. I am not able to reproduce that currently but I will keep an eye on it. Thanks again for the feedback.
