### ISSUE TITLE
Launch default URL on page load

### ISSUE THREAD

**Issue by chrisdubya-mango** [DustinBrett/x#9]
Hi,

I just want to preface that this site is a masterpiece.  

I was trying to go about launching a program (i.e. Doom.url) on page load.

I noticed that the `IconEntry` component has a `onDoubleClick` function that seems to trigger this, but I feel that manually triggering this function would be bad practice.  Do you have any suggestions based on how you would approach this feature?

Thanks!

**Comment by DustinBrett** [comment]
Thank you!

I did indeed have an idea for that involving special URL's, I have it on a to do list somewhere. The basic idea is something like going to `https://x.dustinbrett.com/games/doom.jsdos` or `https://x.dustinbrett.com/#doom` would load the game. I just need some kind of onload checker of the URL, because there already is some fake logic for loading these URL's which is why the Doom shortcut is actually a real file `https://github.com/DustinBrett/x/blob/master/public/desktop/Doom.url`.

Thank you for the note and I will explicitly add this as a feature request when I have a moment.

I just started a new job this week so I've had less time than usual.

**Comment by chrisdubya-mango** [comment]
I was able to achieve this by duplicating the `onDoubleClick` function without a mouse event and pass an Icon component ref along with the other arguments instead of an `EventTarget` for the `processId`.  Then I added a `useEffect` hook to `IconEntry` that will trigger this function on render if the title matches whatever is specified as my default.

Feels a bit hacky and redundant, but it works!

Thanks again and congrats on the new gig!
